/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./src/components/AddTodo.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    ListTodo: typeof import('./src/components/ListTodo.vue')['default']
  }
}
